import{i as c,S as u}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const i={form:document.querySelector("form"),inputSearch:document.querySelector("input"),imageContainer:document.querySelector(".gallery"),loader:document.querySelector(".loader")};function l(){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}function p(e){return`<li class="gallery-item">
            <a class="gallery-link" href="${e.largeImageURL}">
              <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" />
            </a>
               <ul class="list-content">      
                  <li class="list-text"><p>Likes <span>${e.likes}</span></p></li>
                  <li class="list-text"><p>Views <span>${e.views}</span></p></li>
                  <li class="list-text"><p>Comments <span>${e.comments}</span></p></li>
                  <li class="list-text"><p>Downloads <span>${e.downloads}</span></p></li>
              </ul>
          </li>`}function f(e){const o=e.hits.map(p).join("");if(!e.hits.length)l();else{i.imageContainer.innerHTML=o;const n=new u(".gallery a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250});n.on("show.simplelightbox"),n.refresh()}}function m(e){const n=`https://pixabay.com/api/?${new URLSearchParams({key:"42406888-248cc758d404d4e51dcff55ab",q:`${e}`,image_type:"photo",orientation:"horizontal",safesearch:!0})}`;return fetch(n).then(s=>{if(!s.ok)throw new Error(s.status);return s.json()})}function d(){i.loader.classList.remove("hidden")}function h(){i.loader.classList.add("hidden")}function g(e){return e.trim()!==""}function y(e){e.preventDefault();const o=e.target.elements.query.value;if(!g(o)){l();return}d(),i.imageContainer.innerHTML="",m(o).then(f).catch(l).finally(h),e.target.reset()}i.form.addEventListener("submit",y);
//# sourceMappingURL=commonHelpers.js.map
