import{i as c,S as u}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const i={form:document.querySelector("form"),inputSearch:document.querySelector("input"),imageContainer:document.querySelector(".gallery"),loader:document.querySelector(".loader")};function l(){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}function p(e){return`<li class="gallery-item">
            <a class="gallery-link" href="${e.largeImageURL}">
              <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" />
            </a>
               <ul class="list-content">      
                  <li class="list-text"><p>Likes <span>${e.likes}</span></p></li>
                  <li class="list-text"><p>Views <span>${e.views}</span></p></li>
                  <li class="list-text"><p>Comments <span>${e.comments}</span></p></li>
                  <li class="list-text"><p>Downloads <span>${e.downloads}</span></p></li>
              </ul>
          </li>`}function m(e){const o=e.hits.map(p).join("");if(!e.hits.length)l();else{i.imageContainer.innerHTML=o;const s=new u(".gallery a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250});s.on("show.simplelightbox"),s.refresh()}}function d(e){const s=`https://pixabay.com/api/?${new URLSearchParams({key:"42406888-248cc758d404d4e51dcff55ab",q:`${e}`,image_type:"photo",orientation:"horizontal",safesearch:!0})}`;return fetch(s).then(n=>{if(!n.ok)throw new Error(n.status);return n.json()})}function f(){i.loader.classList.remove("hidden")}function h(){i.loader.classList.add("hidden")}function g(e){e.preventDefault(),f(),i.imageContainer.innerHTML="";const o=e.target.elements.query.value;d(o).then(m).catch(l).finally(h),e.target.reset()}i.form.addEventListener("submit",g);
//# sourceMappingURL=commonHelpers.js.map
