import{i as c,S as u}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();const n={form:document.querySelector("form"),inputSearch:document.querySelector("input"),imageContainer:document.querySelector(".gallery"),loader:document.querySelector(".loader")};function a(){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}function p(e){return`<li class="gallery-item">
            <a class="gallery-link" href="${e.largeImageURL}">
              <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" />
            </a>
               <ul class="list-content">      
                  <li class="list-text"><p>Likes <span>${e.likes}</span></p></li>
                  <li class="list-text"><p>Views <span>${e.views}</span></p></li>
                  <li class="list-text"><p>Comments <span>${e.comments}</span></p></li>
                  <li class="list-text"><p>Downloads <span>${e.downloads}</span></p></li>
              </ul>
          </li>`}function d(e){const o=e.hits.map(p).join("");if(!e.hits.length)a();else{n.imageContainer.innerHTML=o;const i=new u(".gallery a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250});i.on("show.simplelightbox"),i.refresh()}}function f(e){return fetch(url).then(o=>{if(!o.ok)throw new Error(o.status);return o.json()})}function m(){n.loader.classList.remove("hidden")}function h(){n.loader.classList.add("hidden")}function g(e){e.preventDefault(),m(),n.imageContainer.innerHTML="",e.target.elements.query.value,f().then(d).catch(a).finally(h),e.target.reset()}n.form.addEventListener("submit",g);
//# sourceMappingURL=commonHelpers.js.map
